version: "2"

services:
  django-apache2:
    build: .
    container_name: mtel-2024-apache2
    ports:
      - '8881:443'
    volumes:
      - $PWD.:/var/www/html:rw
      - /etc/letsencrypt/:/etc/letsencrypt/