version: "2"

services:
  django-apache2:
    build: .
    container_name: django-apache2
    ports:
      - '8881:8881'
      - '81:81'
    volumes:
      - $PWD.:/var/www/html:rw
      - /etc/letsencrypt/:/etc/letsencrypt/